version: '3.8'

services:
  web:
    build:
      context: ./project
      dockerfile: Dockerfile.django
    command: >
        sh -c "python manage.py collectstatic --no-input --clear &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./project/:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=*