version: '3.8'

services:
  web:
    build:
      context: ./project
      dockerfile: Dockerfile.django
    command: >
        sh -c "python manage.py collectstatic --no-input --clear &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./project/:/usr/src/app/
    ports:
      - 8000:8000

  emitter:
    build:
      context: ./emitter
      dockerfile: Dockerfile.emitter
    volumes:
      - ./emitter/:/usr/src/app/

  meteo:
    build:
      context: ./meteo
      dockerfile: Dockerfile.meteo
    command: >
        sh -c "python app.py"
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./meteo:/usr/src/app/
