# Generated by Django 3.2.5 on 2023-09-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('datetime', models.DateTimeField()),
                ('speed_overground', models.FloatField()),
                ('stw', models.FloatField()),
                ('direction', models.FloatField()),
                ('current_ucomp', models.FloatField()),
                ('current_vcomp', models.FloatField()),
                ('draft_aft', models.FloatField()),
                ('draft_fore', models.FloatField()),
                ('comb_wind_swell_wave_height', models.FloatField()),
                ('power', models.FloatField()),
            ],
        ),
    ]
