# Generated by Django 3.2.5 on 2023-09-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsdata', '0002_auto_20230914_0752'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorDataNormalized',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('speed_overground', models.FloatField(blank=True, null=True)),
                ('stw', models.FloatField(blank=True, null=True)),
                ('direction', models.FloatField(blank=True, null=True)),
                ('current_ucomp', models.FloatField(blank=True, null=True)),
                ('current_vcomp', models.FloatField(blank=True, null=True)),
                ('draft_aft', models.FloatField(blank=True, null=True)),
                ('draft_fore', models.FloatField(blank=True, null=True)),
                ('comb_wind_swell_wave_height', models.FloatField(blank=True, null=True)),
                ('power', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sensordata',
            name='latitude_correction',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
