# Generated by Django 3.2.5 on 2023-09-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsdata', '0004_auto_20230914_1038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SensorDataNormalized',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='sea_currents_angle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='sea_currents_speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
