# Generated by Django 3.2.5 on 2023-09-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsdata', '0005_auto_20230915_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='sea_currents_angle_correction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='sea_currents_speed_correction',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
